"""
Cross-world TRANSFER evaluation — the panel answer to "every number here comes
from a synthetic world you authored."

Overwatch ships two INDEPENDENTLY designed synthetic worlds:

  world A (worldmodel.py)   reason-dominated: recovery hinges on a reason x action
                            fit matrix. Models trained on it live in ml/artifacts.
  world B (worldmodel2.py)  context-driven: recovery hinges on a latent customer
                            archetype that only leaks through observable customer
                            features. Models trained on it live in ml/artifacts_v2.

Neither generator imports the other. This script FREEZES the models trained on one
world and evaluates them on the other world, in both directions, through the same
code path. If a frozen model still ranks recoveries and picks actions better than
chance-or-rules on a world whose causal mechanism it never saw, that is a real
generalization claim. If it does not, that is a finding and it is reported just as
prominently — fixed seeds, no retraining, no direction dropped.

What is measured per direction (A->B = ml/artifacts scored on world B, and B->A):

  * Recovery transfer.  The frozen source-world calibrated CatBoost scores every
    (case, logged action_taken) row of the ENTIRE target dataset — every row is
    unseen by that model (different generator, different seed, no shared training
    data). Reported: ROC-AUC with a 95% bootstrap CI (train.py's bootstrap_auc_ci,
    resampling cases) and Brier. Context in the same JSON: the frozen LogReg
    baseline's transfer AUC with a paired-bootstrap CatBoost-vs-LogReg diff (does
    the CatBoost edge survive transfer?), and the target world's OWN primary model
    on the same rows — an in-world CEILING that is partially in-sample (it trained
    on the earliest ~80% of those rows), an upper reference, not a fair
    head-to-head.

  * Action-value transfer.  eval.py's counterfactual machinery, graded by the
    TARGET world's ground-truth success_prob (the model only chooses the action —
    it never grades itself): the frozen source-world action head, with the same
    deployed hard-decline guard, picks an action per case; we report its
    incremental net rupees vs the deterministic rules baseline with a 95%
    bootstrap CI. Evaluated on the target world's time-ordered latest-~20% split
    with the same bootstrap seed eval.py uses, so these numbers are directly
    comparable with the in-world figures in eval.json / eval_v2.json — even
    though the frozen model has never seen ANY target-world row, early or late.

Nothing is retrained here: if a model artifact is missing, the script stops with
an error instead of training. A missing CSV is regenerated with that generator's
DEFAULT seed and row count, so every number is deterministic (fixed bootstrap
seeds, no wall-clock anywhere in the output).

Run:  ml/.venv/Scripts/python ml/src/transfer.py      (writes ml/transfer.json)
"""
from __future__ import annotations

import argparse
import inspect
import json
import os

import joblib
import pandas as pd
from sklearn.metrics import roc_auc_score

import eval as evalmod  # reuse the counterfactual machinery (GT, arms, costs, bootstrap)
import worldmodel
import worldmodel2
from features import CASE_FEATURES, recovery_frame
from train import bin_metrics, bootstrap_auc_ci, bootstrap_diff_ci

REQUIRED_LABELS = ["action_taken", "recovered", "day_index"]

# Fixed bootstrap seeds: 42 mirrors train.py's AUC CIs, 123 mirrors eval.py's value
# CIs — identical machinery, so in-world and transfer intervals are comparable.
AUC_CI_SEED = 42
VALUE_CI_SEED = 123


def load_dataset(path: str, module, extra_cols: list[str], regen_cmd: str):
    """Load a world's CSV; if missing, regenerate it with the module's DEFAULT
    seed/rows (deterministic). Assert the shared schema either way."""
    gen_params = inspect.signature(module.generate).parameters
    default_seed, default_rows = gen_params["seed"].default, gen_params["n_rows"].default
    if os.path.exists(path):
        df = pd.read_csv(path)
        provenance = (
            f"pre-existing CSV (assumed generated with the module default seed {default_seed}; "
            f"regenerate deterministically via `{regen_cmd}`)"
        )
    else:
        print(f"{path} missing — regenerating with {module.__name__}.generate() defaults (seed {default_seed}, rows {default_rows})...")
        df = module.generate()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        df.to_csv(path, index=False)
        provenance = f"regenerated by transfer.py with module defaults (seed {default_seed}, rows {default_rows})"
    missing = [c for c in CASE_FEATURES + REQUIRED_LABELS + extra_cols if c not in df.columns]
    if missing:
        raise SystemExit(f"{path} is missing required columns {missing} — not a valid export of {module.__name__}")
    meta = {
        "path": path,
        "generator": f"ml/src/{module.__name__}.py",
        "rows": int(len(df)),
        "recovered_rate": round(float(df["recovered"].mean()), 4),
        "default_seed": int(default_seed),
        "provenance": provenance,
    }
    return df, meta


def load_bundle(path: str) -> dict:
    """Load a trained artifact. Transfer NEVER trains: a missing file is a hard stop."""
    if not os.path.exists(path):
        raise SystemExit(f"missing artifact {path} — transfer.py refuses to train; run train.py for that world first")
    return joblib.load(path)


def head_actions(art: str, test: pd.DataFrame, rows: list[dict]):
    """The deployed decision path, identical to eval.py's ml_head arm: CatBoost
    action-head argmax over pursuit actions + the hard-decline policy guard."""
    bundle = load_bundle(f"{art}/action_primary.joblib")
    model, classes = bundle["model"], bundle["classes"]
    proba = model.predict_proba(test[CASE_FEATURES])
    allowed = [i for i, c in enumerate(classes) if c in evalmod.PURSUIT]
    acts = [
        evalmod.apply_policy_guard(classes[max(allowed, key=lambda i: proba[k][i])], rows[k])
        for k in range(len(rows))
    ]
    return acts, bundle["version"]


def run_direction(label: str, src_art: str, tgt_art: str, tgt_df: pd.DataFrame, tgt_module, tgt_data_path: str, inworld_eval_json: str, boot: int) -> dict:
    print(f"\n--- direction {label}: frozen {src_art} scored on {tgt_data_path} ({tgt_module.__name__} ground truth) ---")

    # ---------------- Recovery transfer: ENTIRE target dataset ----------------
    rec = load_bundle(f"{src_art}/recovery_primary.joblib")
    lrg = load_bundle(f"{src_art}/recovery_logreg.joblib")
    own = load_bundle(f"{tgt_art}/recovery_primary.joblib")

    X, y = recovery_frame(tgt_df), tgt_df["recovered"].values
    print(f"recovery: scoring {len(tgt_df)} target rows with the frozen primary / logreg / in-world models...")
    p_cb = rec["model"].predict_proba(X)[:, 1]
    p_lr = lrg["model"].predict_proba(X)[:, 1]
    p_own = own["model"].predict_proba(X)[:, 1]

    print("recovery: bootstrap confidence intervals...")
    m = bin_metrics(y, p_cb)
    recovery = {
        "scored": "P(recover | case, logged action_taken) vs realized `recovered`, on ALL target rows",
        "n_rows_scored": int(len(tgt_df)),
        "auc": m["roc_auc"],
        "auc_ci95": bootstrap_auc_ci(y, p_cb, B=boot, seed=AUC_CI_SEED),
        "brier": m["brier"],
        "pr_auc": m["pr_auc"],
        "logreg_auc": round(float(roc_auc_score(y, p_lr)), 4),
        "logreg_auc_ci95": bootstrap_auc_ci(y, p_lr, B=boot, seed=AUC_CI_SEED),
        "catboost_vs_logreg_transfer": bootstrap_diff_ci(y, p_cb, p_lr, B=boot, seed=AUC_CI_SEED),
        "in_world_ceiling_auc": round(float(roc_auc_score(y, p_own)), 4),
        "in_world_ceiling_note": (
            "the target world's OWN calibrated primary scored on the same rows — PARTIALLY IN-SAMPLE "
            "(it trained on the earliest ~80% of them), so this is ceiling-only context, not a fair head-to-head"
        ),
        "base_rate_note": "Brier depends on the target world's base rate and the frozen calibration; compare within a direction, not across worlds",
    }
    # Fair in-world reference (held-out at train time), read from the target's training report.
    try:
        with open(f"{tgt_art}/metrics.json") as f:
            tm = json.load(f)["recovery"]
        recovery["in_world_heldout_auc_at_train_time"] = {
            "auc": tm["catboost_calibrated"]["roc_auc"],
            "auc_ci95": tm["auc_ci"]["catboost_calibrated"],
            "note": "the target world's own model on its own time-ordered held-out split (from train.py's metrics.json) — the fair in-world number",
        }
    except (OSError, KeyError, json.JSONDecodeError):
        recovery["in_world_heldout_auc_at_train_time"] = None

    # ---------------- Action-value transfer: eval.py machinery, target GT ----------------
    # Same trick eval.main() uses: point the module-level ground-truth scorer at the
    # TARGET world before any collected()/arm_net() call.
    evalmod.GT = tgt_module.success_prob

    # eval.py's exact time-ordered split — kept ONLY so these numbers line up
    # case-for-case with the in-world eval.json / eval_v2.json; the frozen model
    # has seen none of the target world either way.
    order = tgt_df.sort_values("day_index", kind="stable").index
    test = tgt_df.loc[order[int(len(order) * 0.8):]].reset_index(drop=True)
    rows = test.to_dict("records")
    n = len(rows)

    print(f"action: choosing actions for {n} held-out target cases (frozen + in-world heads)...")
    frozen_acts, frozen_action_version = head_actions(src_art, test, rows)
    inworld_acts, _ = head_actions(tgt_art, test, rows)
    arms = {
        "no_action": ["no_action"] * n,
        "rules_only": [evalmod.rules_only_action(r) for r in rows],
        "frozen_head": frozen_acts,
        "in_world_head": inworld_acts,
        "oracle": [max(evalmod.PURSUIT, key=lambda a: evalmod.collected(r, a) - evalmod.ACTION_COST[a]) for r in rows],
    }
    per_case = {name: evalmod.arm_net(rows, acts) for name, acts in arms.items()}

    def lift(arm: str, vs: str) -> dict:
        d = per_case[arm] - per_case[vs]
        total, lo, hi = evalmod.boot_ci(d, n=boot, seed=VALUE_CI_SEED)
        return {
            "net_rupees_total": round(total, 2),
            "total_ci95": [round(lo, 2), round(hi, 2)],
            "net_rupees_per_case": round(total / n, 2),
            "per_case_ci95": [round(lo / n, 2), round(hi / n, 2)],
            "incremental_paise_mean": round(100.0 * total / n, 1),
            "significant": bool(lo > 0 or hi < 0),
        }

    print("action: bootstrap confidence intervals...")
    action_value = {
        "eval_split": (
            "time-ordered latest ~20% of target days — identical split, ground truth and bootstrap seed as the "
            "in-world eval.py run, so these numbers are directly comparable with eval.json / eval_v2.json; "
            "every case is still unseen by the frozen model"
        ),
        "n_cases": n,
        "policy": "frozen source-world CatBoost action head, argmax over pursuit actions, deployed hard-decline guard applied (eval.apply_policy_guard)",
        "frozen_vs_rules": lift("frozen_head", "rules_only"),
        "frozen_vs_no_action": lift("frozen_head", "no_action"),
        "in_world_vs_rules": {
            **lift("in_world_head", "rules_only"),
            "note": f"context: the TARGET world's own action head on the same cases — matches {inworld_eval_json} incremental_lift_primary.vs_rules_only",
        },
        "arm_net_rupees": {name: round(float(v.sum()), 2) for name, v in per_case.items()},
        "frozen_action_mix": {a: frozen_acts.count(a) for a in sorted(set(frozen_acts))},
        "rules_baseline_note": (
            "deterministic error-reason triage (eval.rules_only_action); every arm is graded by the TARGET world's "
            "ground-truth success_prob — models only CHOOSE actions, they never grade themselves"
        ),
        "units": "rupees (paise = rupees x 100)",
    }

    return {
        "direction": label,
        "frozen_artifacts": src_art,
        "frozen_model_version": {"recovery": rec["version"], "action": frozen_action_version},
        "target_dataset": tgt_data_path,
        "target_ground_truth": f"{tgt_module.__name__}.success_prob",
        "n_rows": int(len(tgt_df)),
        "unseen_note": (
            "every target-world row is unseen by the frozen source-world models: the worlds are separate "
            "generators with different seeds and different causal mechanisms, and nothing is retrained here"
        ),
        "recovery": recovery,
        "action_value": action_value,
    }


def main(args) -> None:
    df_a, meta_a = load_dataset(args.data_a, worldmodel, [], "python ml/src/worldmodel.py --out ml/data/train.csv")
    df_b, meta_b = load_dataset(args.data_b, worldmodel2, ["_archetype"], "python ml/src/worldmodel2.py --out ml/data/train_v2.csv")

    directions = {
        "A_to_B": run_direction("A->B", args.art_a, args.art_b, df_b, worldmodel2, args.data_b, "eval_v2.json", args.boot),
        "B_to_A": run_direction("B->A", args.art_b, args.art_a, df_a, worldmodel, args.data_a, "eval.json", args.boot),
    }

    report = {
        "purpose": (
            "cross-world transfer of FROZEN models between two independently designed synthetic worlds — "
            "the defense against 'every number is on a world you wrote': signal that survives on a world "
            "the model never saw is generalization, not memorized world quirks"
        ),
        "method": {
            "frozen": "models are loaded from the source world's artifacts and never retrained or refit",
            "recovery_metric": "ROC-AUC + Brier of the frozen recovery head on the ENTIRE target dataset (all rows unseen)",
            "action_value_metric": "incremental net rupees of the frozen action head vs the deterministic rules baseline, graded by the target world's ground-truth value function on its time-ordered held-out split",
            "bootstrap": {"draws": args.boot, "auc_ci_seed": AUC_CI_SEED, "value_ci_seed": VALUE_CI_SEED, "resampling": "cases (rows), matching train.py / eval.py"},
            "determinism": "fixed seeds everywhere; no wall-clock enters any number",
        },
        "datasets": {"A": meta_a, "B": meta_b},
        "directions": directions,
    }
    with open(args.out, "w") as f:
        json.dump(report, f, indent=2)

    # ---- console table (ASCII only — Windows consoles choke on the rupee glyph) ----
    print("\n================ CROSS-WORLD TRANSFER (frozen models, no retraining) ================")
    print("\nRecovery head - ROC-AUC on the ENTIRE target dataset (every row unseen by the frozen model)")
    print(f"{'direction':<10} {'frozen AUC [95% CI]':<28} {'Brier':>7} {'frozen LogReg AUC':>18} {'in-world ceiling*':>18}")
    for d in directions.values():
        r = d["recovery"]
        ci = r["auc_ci95"]
        print(f"{d['direction']:<10} {r['auc']:.4f} [{ci[0]:.4f}, {ci[1]:.4f}]{'':<6} {r['brier']:>7.4f} {r['logreg_auc']:>18.4f} {r['in_world_ceiling_auc']:>18.4f}")
    print("* target world's own model on the same rows - partially in-sample; upper reference only")

    print("\nAction head - net Rs vs rules baseline on the target's held-out split (95% CI; target-world ground truth)")
    print(f"{'direction':<10} {'frozen head vs rules':<42} {'per-case Rs':>12} {'in-world head vs rules':>24}")
    for d in directions.values():
        v = d["action_value"]
        fr, iw = v["frozen_vs_rules"], v["in_world_vs_rules"]
        sig = "sig" if fr["significant"] else "n.s."
        print(
            f"{d['direction']:<10} {fr['net_rupees_total']:>+14,.0f} [{fr['total_ci95'][0]:>+13,.0f}, {fr['total_ci95'][1]:>+13,.0f}] {sig:<4} "
            f"{fr['net_rupees_per_case']:>+12,.2f} {iw['net_rupees_total']:>+24,.0f}"
        )
    print("\nwrote", args.out)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Cross-world transfer eval: frozen world-A models on world B, and vice versa.")
    ap.add_argument("--data-a", default="ml/data/train.csv", help="world A dataset (regenerated with default seed if missing)")
    ap.add_argument("--data-b", default="ml/data/train_v2.csv", help="world B dataset (regenerated with default seed if missing)")
    ap.add_argument("--art-a", default="ml/artifacts", help="world A artifacts (frozen; never retrained)")
    ap.add_argument("--art-b", default="ml/artifacts_v2", help="world B artifacts (frozen; never retrained)")
    ap.add_argument("--out", default="ml/transfer.json")
    ap.add_argument("--boot", type=int, default=1000, help="bootstrap draws for every CI")
    main(ap.parse_args())
